import { TaskConfig } from './types';

export const TASK_CONFIGS: Record<number, TaskConfig> = {
  1: {
    id: 1,
    title: "Aufgabe 1: Sich informieren",
    description: "Telephone inquiry (Formal)",
    prepTimeSeconds: 30,
    speakTimeSeconds: 30,
    context: "Sie (Formal)",
    interlocutor: "University Staff",
  },
  2: {
    id: 2,
    title: "Aufgabe 2: Berichten",
    description: "Describe home country (Informal)",
    prepTimeSeconds: 60,
    speakTimeSeconds: 60,
    context: "Du (Informal)",
    interlocutor: "Friend/Classmate",
  },
  3: {
    id: 3,
    title: "Aufgabe 3: Grafik beschreiben",
    description: "Describe a chart (Formal)",
    prepTimeSeconds: 60,
    speakTimeSeconds: 90,
    context: "Sie (Formal)",
    interlocutor: "Professor",
  },
  4: {
    id: 4,
    title: "Aufgabe 4: Stellung nehmen",
    description: "Argue a position (Formal)",
    prepTimeSeconds: 180,
    speakTimeSeconds: 120,
    context: "Sie (Formal)",
    interlocutor: "Professor",
  },
  5: {
    id: 5,
    title: "Aufgabe 5: Abwägen",
    description: "Give advice/Weigh options (Informal)",
    prepTimeSeconds: 120,
    speakTimeSeconds: 90,
    context: "Du (Informal)",
    interlocutor: "Friend",
  },
  6: {
    id: 6,
    title: "Aufgabe 6: Hypothesen bilden",
    description: "Analyze reasons/consequences (Formal)",
    prepTimeSeconds: 180,
    speakTimeSeconds: 120,
    context: "Sie (Formal)",
    interlocutor: "Professor",
  },
  7: {
    id: 7,
    title: "Aufgabe 7: Rat geben",
    description: "Give advice on a problem (Informal)",
    prepTimeSeconds: 90,
    speakTimeSeconds: 90,
    context: "Du (Informal)",
    interlocutor: "Friend",
  },
};